### ISSUE TITLE
I have a client side problem

### ISSUE THREAD

**Issue by qews642** [Pycckue-Bnepeg/samp-cef#31]
I have a problem that is that it detects me as if I did not have the plugin installed, when it does not have it I have all the files and within the game it returns false in OnCefInitialize and cef_player_has_plugin, most likely it is me by not installing it correctly, if you could Make me a mini tutorial on how to install it, I would appreciate it. (client side)

**Comment by Rams25** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/60780565/150490735-f1dc4ded-ddba-49ff-a1d0-3245e4a54a1f.png)
create CEF folder in game root and put theses files
put cef.asi in game root

Sometime u can have problem with first play, retry

**Comment by nnee2810** [comment]
> ![Screenshot_1](https://user-images.githubusercontent.com/60780565/150490735-f1dc4ded-ddba-49ff-a1d0-3245e4a54a1f.png) create CEF folder in game root and put theses files put cef.asi in game root
> 
> Sometime u can have problem with first play, retry
Can you upload zip folder

**Comment by MeIsAlan** [comment]
I'm having the exact same problem with it, I've tried the game multiple times now and nothing.

**Comment by Pycckue-Bnepeg** [comment]
хуево вам

**Comment by KenKup** [comment]
@Pycckue-Bnepeg кому хуево?

**Comment by Cheaterman** [comment]
IDK if we should keep this closed? Instructions on finding a suitable CEF prebuilt distribution aren't provided, and my own attempts with [semi-official builds](https://cef-builds.spotifycdn.com/cef_binary_89.0.5%2Bgc1f90d8%2Bchromium-89.0.4389.40_windows32_beta.tar.bz2) didn't work too well (despite trying my best to reproduce the folder structure above, by merging Release and Resources folders directly into `GTA_root/cef`).

It's worth noting in my specific case I'm running SAMP from Wine however (I'm running Linux) so it may just not work at all for whatever reason. In any case, I have an ASI loader and several other ASIs load fine (SAMPFUNCS and Moonloader for example). Is there a way you could provide some debugging instructions @Pycckue-Bnepeg ? Maybe some log files to look into? 

Thanks in advance!
