### ISSUE TITLE
Масштабирование

### ISSUE THREAD

**Issue by walkerdevelop** [Pycckue-Bnepeg/samp-cef#46]
Привет, натянул на объект браузер через cef_create_ext_browser, так у меня вместо одного цельного браузера получились плитки:
![image](https://user-images.githubusercontent.com/48883001/221413257-10f44c9e-b8b3-4d23-b745-ce8194b1d7ba.png)
Можно ли как то исправить это?

**Comment by Pycckue-Bnepeg** [comment]
выбрать правильную текстуру

**Comment by walkerdevelop** [comment]
> 

![image](https://user-images.githubusercontent.com/48883001/221429902-ec7b99c1-007b-46bb-bd35-ba74475da8ca.png)

19456 стена сампа,
самодельные объекты (даже тупо один прямоугольник)
везде траблы(

**Comment by WestSide56** [comment]
Используй объекты, где текстура не дублируется.
Например 7912, заменяемая текстура bobobillboard1

**Comment by walkerdevelop** [comment]
Спасибо, помогло
Сколько ж я с этим мучался, ээх

**Comment by electronjs1** [comment]
@WestSide56 Не ожидал тебя здесь увидеть :)
